---
title: "SMD Graph"
author: "Brian Kim"
date: "26/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(ggplot2)
library(tidyverse)
library(readxl)
library(janitor)
library(gt)
library(rvest)
library(forcats)
library(stringr)
library(magrittr)
library(reprex)
library(gganimate)
library(magick)
library(ggforce)
# library(transformr)

# used devtools::install_github("thomasp85/transformr") to install transformr package
```

```{r Pulling SMD, echo = FALSE}

# CONTINUED from smd_datacleaning

# read in the excel file, Single Member District Excel sheet

SMD_partyshare <- read.csv("raw-data/SMD_partyshare.csv") %>%
  clean_names()


```



```{r Trying New Graph, echo = FALSE}

# ggplot by ideology

graphSMD <- SMD_partyshare %>%
  ggplot(aes(x = year, y = averagevoteshare, color = factor(cons_or_not))) +
  geom_line(show.legend = FALSE) +
  facet_wrap_paginate(~region,
                     nrow = 1, 
                     ncol = 1, 
                     scales = "free") +
  scale_colour_manual(values = c("blue", "red", "black")) + 
  
  # scale the years
  scale_x_continuous(breaks = seq(1988, 2016, by = 4),
                       labels = c("1988", "'92", "'96", "2000",
                                "'04", "'08", "'12", "'16")) +

  # scale the percentage
  scale_y_continuous(breaks = seq(10, 100, by = 10),
                       limits = c(0, 100)) +

  # add title to graph
  labs(title = "Vote Shares for Single Member Districts Seats Nationwide",
         subtitle = "Current system started in 1996",
         caption  = "Data from Kuniaki Nemoto, Musashi University", 
       y = "Percent", x = "Year") +
  
  # add text 
    annotate(geom = "text", x = 1992, y = 80, 
             label = "Conservatives", color = "Red", size = 5) +
    annotate(geom = "text", x = 1992, y = 25, 
             label = "Liberal/Progressives", color = "Blue", size = 5) +

  theme_classic()

graphSMD

```


